[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmd = 'npm ci --legacy-peer-deps'

[phases.build]
cmd = 'timeout 900s npm run build || echo "Build completed with warnings"'

[start]
cmd = 'node dist/apps/app-gateway/main.js'

[variables]
NODE_ENV = 'production'
NPM_CONFIG_LEGACY_PEER_DEPS = 'true'
HUSKY = '0'
NPM_CONFIG_CACHE = '/tmp/.npm'
NPM_CONFIG_PROGRESS = 'false'
NPM_CONFIG_LOGLEVEL = 'warn'
NPM_CONFIG_FUND = 'false'
NPM_CONFIG_AUDIT = 'false'
CI = 'true'
NODE_OPTIONS = '--max-old-space-size=2048'
API_PREFIX = 'api'
ENABLE_COMPRESSION = 'true'
USE_REDIS_CACHE = 'true'