# AlertManager配置 - 告警路由和通知
global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@ai-recruitment.com'
  smtp_auth_username: 'alerts@ai-recruitment.com'
  smtp_auth_password: 'your-smtp-password'

route:
  group_by: ['alertname', 'service', 'severity']
  group_wait: 10s
  group_interval: 10m
  repeat_interval: 1h
  receiver: 'default'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
    - match:
        severity: warning
      receiver: 'warning-alerts'
    - match:
        service: database
      receiver: 'database-alerts'
    - match:
        service: messaging
      receiver: 'messaging-alerts'

receivers:
  - name: 'default'
    webhook_configs:
    - url: 'http://localhost:3000/api/alerts/webhook'
      send_resolved: true

  - name: 'critical-alerts'
    webhook_configs:
    - url: 'http://localhost:3000/api/alerts/critical'
      send_resolved: true

  - name: 'warning-alerts'
    webhook_configs:
    - url: 'http://localhost:3000/api/alerts/warning'
      send_resolved: true

  - name: 'database-alerts'
    webhook_configs:
    - url: 'http://localhost:3000/api/alerts/database'
      send_resolved: true

  - name: 'messaging-alerts'
    webhook_configs:
    - url: 'http://localhost:3000/api/alerts/messaging'
      send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service', 'instance']