# Prometheus Configuration for AI Recruitment Clerk
# Production monitoring and alerting setup

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ai-recruitment-production'
    environment: 'production'

# Rule files for alerting
rule_files:
  - "alerts/*.yml"

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # AI Recruitment services monitoring
  - job_name: 'app-gateway'
    static_configs:
      - targets: ['app-gateway:9090']
    scrape_interval: 10s
    metrics_path: /metrics
    basic_auth:
      username: 'prometheus'
      password: 'monitoring-password'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'app-gateway'
      - source_labels: [__address__]
        target_label: service
        replacement: 'gateway'

  - job_name: 'jd-extractor-svc'
    static_configs:
      - targets: ['jd-extractor-svc:9090']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'jd-extractor'
      - source_labels: [__address__]
        target_label: service
        replacement: 'jd-extractor'

  - job_name: 'resume-parser-svc'
    static_configs:
      - targets: ['resume-parser-svc:9090']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'resume-parser'
      - source_labels: [__address__]
        target_label: service
        replacement: 'resume-parser'

  - job_name: 'scoring-engine-svc'
    static_configs:
      - targets: ['scoring-engine-svc:9090']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'scoring-engine'
      - source_labels: [__address__]
        target_label: service
        replacement: 'scoring-engine'

  - job_name: 'report-generator-svc'
    static_configs:
      - targets: ['report-generator-svc:9090']
    scrape_interval: 20s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'report-generator'
      - source_labels: [__address__]
        target_label: service
        replacement: 'report-generator'

  # Infrastructure monitoring
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'mongodb'
      - source_labels: [__address__]
        target_label: service
        replacement: 'database'

  - job_name: 'nats'
    static_configs:
      - targets: ['nats:7777']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'nats'
      - source_labels: [__address__]
        target_label: service
        replacement: 'messaging'

  # System monitoring
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'host-system'
      - source_labels: [__address__]
        target_label: service
        replacement: 'system'

  # Container monitoring
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'containers'
      - source_labels: [__address__]
        target_label: service
        replacement: 'containers'

  # Frontend monitoring (if enabled)
  - job_name: 'nginx'
    static_configs:
      - targets: ['ai-recruitment-frontend:9113']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'frontend'
      - source_labels: [__address__]
        target_label: service
        replacement: 'web-server'

# Remote storage configurations disabled - no external storage configured
# remote_write:
#   - url: "http://remote-storage:9201/write"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500

# remote_read:
#   - url: "http://remote-storage:9201/read"
#     read_recent: true