services:
  # MongoDB for E2E testing
  mongodb-e2e:
    image: mongo:7
    container_name: mongodb-e2e
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: testpass123
      MONGO_INITDB_DATABASE: ai-recruitment-test
    volumes:
      - mongodb-e2e-data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - e2e-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/ai-recruitment-test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Redis for caching in E2E testing
  redis-e2e:
    image: redis:7-alpine
    container_name: redis-e2e
    ports:
      - "6380:6379"
    volumes:
      - redis-e2e-data:/data
      - ./config/redis-test.conf:/usr/local/etc/redis/redis.conf:ro
    networks:
      - e2e-network
    command: redis-server /usr/local/etc/redis/redis.conf
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # NATS for message bus in E2E testing
  nats-e2e:
    image: nats:latest
    container_name: nats-e2e
    ports:
      - "4223:4222"
      - "8223:8222"  # HTTP monitoring
    networks:
      - e2e-network
    command: ["--js", "--http_port", "8222"]
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mongodb-e2e-data:
    driver: local
  redis-e2e-data:
    driver: local

networks:
  e2e-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16