# Grafana数据源配置 - Prometheus
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: GET
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.54.0
      cacheLevel: 'High'
      disableMetricsLookup: false
      customQueryParameters: ''
      incrementalQueryOverlapWindow: 10m