# 形式化的API规约 (片段)
openapi: 3.0.1
info:
  title: AI Recruitment Clerk API
  version: 1.0.0
paths:
  /jobs/{jobId}/resumes:
    post:
      summary: 为指定岗位批量上传简历
      parameters:
        - name: jobId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobId:
                    type: string
                  submittedResumes:
                    type: integer
